# name: sample-flask
# services:
# - name: web
#   github:
#     repo: digitalocean/sample-flask
#     branch: main

name: eqr-hackathon
services:
  - name: web
    build_command: pip install -r requirements.txt
    run_command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    environment:
      - PYTHON_VERSION=3.9